// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Stores GitHub webhook events for push, issue_comment, and pull_request events
type WebhookEvent struct {
	ID             int32              `json:"id"`
	DeliveryID     string             `json:"delivery_id"`
	EventType      string             `json:"event_type"`
	RepositoryName pgtype.Text        `json:"repository_name"`
	SenderLogin    pgtype.Text        `json:"sender_login"`
	Action         pgtype.Text        `json:"action"`
	Payload        []byte             `json:"payload"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
